[pytest]
asyncio_mode = "auto"
addopts = [
    "--import-mode=importlib",
    "--cov=album_tracker_api",
    "--cov-branch",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-report=xml",
]
strict = true
