"""Album and Collection related models

Revision ID: fa8af8c19c94
Revises: 3cc7be3cdaaf
Create Date: 2026-05-10 18:16:06.124270

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa8af8c19c94"
down_revision: Union[str, Sequence[str], None] = "3cc7be3cdaaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "album",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_album_slug"), "album", ["slug"], unique=True)
    op.create_table(
        "album_section",
        sa.Column("album_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["album_id"], ["album.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("album_id", "order_index", name="uq_section_album_order"),
    )
    op.create_index(op.f("ix_album_section_album_id"), "album_section", ["album_id"], unique=False)
    op.create_table(
        "user_collection",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("album_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["album_id"], ["album.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_collection_album_id"), "user_collection", ["album_id"], unique=False)
    op.create_index(op.f("ix_user_collection_user_id"), "user_collection", ["user_id"], unique=False)
    op.create_table(
        "card",
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["section_id"], ["album_section.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("section_id", "code", name="uq_card_section_code"),
        sa.UniqueConstraint("section_id", "order_index", name="uq_card_section_order"),
    )
    op.create_index(op.f("ix_card_section_id"), "card", ["section_id"], unique=False)
    op.create_table(
        "user_card",
        sa.Column("user_collection_id", sa.Uuid(), nullable=False),
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity >= 0", name="ck_user_card_quantity_non_negative"),
        sa.ForeignKeyConstraint(["card_id"], ["card.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_collection_id"], ["user_collection.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_collection_id", "card_id", name="uq_user_collection_card"),
    )
    op.create_index(op.f("ix_user_card_card_id"), "user_card", ["card_id"], unique=False)
    op.create_index(op.f("ix_user_card_user_collection_id"), "user_card", ["user_collection_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_card_user_collection_id"), table_name="user_card")
    op.drop_index(op.f("ix_user_card_card_id"), table_name="user_card")
    op.drop_table("user_card")
    op.drop_index(op.f("ix_card_section_id"), table_name="card")
    op.drop_table("card")
    op.drop_index(op.f("ix_user_collection_user_id"), table_name="user_collection")
    op.drop_index(op.f("ix_user_collection_album_id"), table_name="user_collection")
    op.drop_table("user_collection")
    op.drop_index(op.f("ix_album_section_album_id"), table_name="album_section")
    op.drop_table("album_section")
    op.drop_index(op.f("ix_album_slug"), table_name="album")
    op.drop_table("album")
    # ### end Alembic commands ###
