"""Add code column to AlbumSection

Revision ID: cc55d510530b
Revises: a9c6c602801a
Create Date: 2026-05-29 14:11:13.661327

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc55d510530b"
down_revision: Union[str, Sequence[str], None] = "a9c6c602801a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 1. Add column as nullable
    op.add_column("album_section", sa.Column("code", sa.String(), nullable=True))

    # 2. Set values to new column
    op.execute("UPDATE album_section SET code = name WHERE code IS NULL")

    # 3. Make column non-nullable
    op.alter_column("album_section", "code", nullable=False)
    op.create_unique_constraint("uq_section_album_code", "album_section", ["album_id", "code"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_section_album_code", "album_section", type_="unique")
    op.drop_column("album_section", "code")
    # ### end Alembic commands ###
