"""TimestampMixin with created_at and updated_at

Revision ID: a9c6c602801a
Revises: fa8af8c19c94
Create Date: 2026-05-29 14:08:33.673540

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9c6c602801a"
down_revision: Union[str, Sequence[str], None] = "fa8af8c19c94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "album", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column(
        "album", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column(
        "album_section",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column(
        "album_section",
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_unique_constraint("uq_section_album_name", "album_section", ["album_id", "name"])
    op.add_column(
        "card", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column(
        "card", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column(
        "user", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column(
        "user", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column(
        "user_card",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column(
        "user_card",
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column(
        "user_collection",
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_collection", "updated_at")
    op.drop_column("user_card", "updated_at")
    op.drop_column("user_card", "created_at")
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("card", "updated_at")
    op.drop_column("card", "created_at")
    op.drop_constraint("uq_section_album_name", "album_section", type_="unique")
    op.drop_column("album_section", "updated_at")
    op.drop_column("album_section", "created_at")
    op.drop_column("album", "updated_at")
    op.drop_column("album", "created_at")
    # ### end Alembic commands ###
